// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_uQCe3nKltn7AhhAcq4BWnkGx3dREsio',
    appId: '1:451906433817:web:083168ef1c9846b7364b88',
    messagingSenderId: '451906433817',
    projectId: 'move-app-9ad02',
    authDomain: 'move-app-9ad02.firebaseapp.com',
    storageBucket: 'move-app-9ad02.firebasestorage.app',
    measurementId: 'G-FKYZTDQFSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaB080jWn_JECvBPKSjoAjs-inuZuQwtA',
    appId: '1:451906433817:android:6fa8d10d069faa20364b88',
    messagingSenderId: '451906433817',
    projectId: 'move-app-9ad02',
    storageBucket: 'move-app-9ad02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9P5JM_ZCbKJt4Y53j5fIFR3-3zc_ayno',
    appId: '1:451906433817:ios:db2e4fe6ac44a924364b88',
    messagingSenderId: '451906433817',
    projectId: 'move-app-9ad02',
    storageBucket: 'move-app-9ad02.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9P5JM_ZCbKJt4Y53j5fIFR3-3zc_ayno',
    appId: '1:451906433817:ios:db2e4fe6ac44a924364b88',
    messagingSenderId: '451906433817',
    projectId: 'move-app-9ad02',
    storageBucket: 'move-app-9ad02.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_uQCe3nKltn7AhhAcq4BWnkGx3dREsio',
    appId: '1:451906433817:web:9391c90c4562c12b364b88',
    messagingSenderId: '451906433817',
    projectId: 'move-app-9ad02',
    authDomain: 'move-app-9ad02.firebaseapp.com',
    storageBucket: 'move-app-9ad02.firebasestorage.app',
    measurementId: 'G-L0FPCPZ2Q3',
  );
}
